service: SplitXMLaddToDynamodb

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  role: arn:aws:iam::233784350905:role/addPersonAdmin
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*'

custom:
  xmlFileBucket: files-will-be-processed-to-sqs-here

resources:
  Resources:
    queueForXMLfile:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: xml-file-added-to-queue
    queueForUpdateFile:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: updated-data-object-queue
    queueForDeleteFile:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: delete-data-object-queue

functions:
  uploadFile:
    handler: src/functions/uploadFile.handler
    events:
      - http:
          path: /file-upload
          method: post
          cors:
            origin: '*' 
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  getData:
    handler: src/functions/getData.handler
    events:
      - http:
          path: /get-data
          method: get
          cors:
            origin: '*' 
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  createData:
    handler: src/functions/createData.handler
    events:
      - http:
          path: /create-data
          method: post
          cors:
            origin: '*' 
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  deleteData:
    handler: src/functions/deleteData.handler
    events:
      - http:
          path: /delete-data
          method: post
          cors:
            origin: '*' 
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  updateData:
    handler: src/functions/updateData.handler
    events:
      - http:
          path: /update-data
          method: post
          cors:
            origin: '*' 
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  SQSsendUpdateMessage:
    handler: src/functions/SQSsendUpdateMessage.handler
    events:
      - http:
          path: /send-update-message
          method: post
          cors:
            origin: '*' 
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  SQSsendDeleteMessage:
    handler: src/functions/SQSsendDeleteMessage.handler
    events:
      - http:
          path: /send-delete-message
          method: post
          cors:
            origin: '*' 
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  S3ListenForCreate:
    handler: src/functions/S3ListenForCreate.handler
    events:
      - s3:
          bucket: ${self:custom.xmlFileBucket}
          event: s3:ObjectCreated:*

  SQSListenForCreateMessage:
    handler: src/functions/SQSListenForCreateMessage.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:233784350905:xml-file-added-to-queue

  SQSListenForUpdateMessage:
    handler: src/functions/SQSListenForUpdateMessage.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:233784350905:updated-data-object-queue

  SQSListenForDeleteMessage:
    handler: src/functions/SQSListenForDeleteMessage.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:233784350905:delete-data-object-queue

  # OpenSearchIndexCreate:
  #   handler: src/functions/OpenSearchIndexCreate.handler

  # OpenSearchIndexSearch:
  #   handler: src/functions/OpenSearchIndexSearch.handler






